import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { config as loadEnv } from "dotenv";
const here = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: join(here, "..", "..", ".env.local") });
const url = process.env.VITE_SUPABASE_URL!;
const ref = new URL(url).hostname.split(".")[0];
const password = process.env.SUPABASE_DB_PASSWORD!;
const c = new pg.Client({ connectionString: `postgresql://postgres.${ref}:${encodeURIComponent(password)}@aws-0-eu-west-1.pooler.supabase.com:5432/postgres`, ssl: { rejectUnauthorized: false } });
await c.connect();
console.log("=== posts whose content_md contains an image ![ or <img or blob url ===");
const r = (await c.query(`select id, title, status from public.posts where content_md ~ '!\\[' or content_md ilike '%<img%' or content_md ilike '%blob.vercel%' order by id desc limit 20`)).rows;
console.log(r);
console.log("count:", r.length);
console.log("\n=== sample image markdown lines ===");
const s = (await c.query(`select id, substring(content_md from '!\\[[^\\n]*') snippet from public.posts where content_md ~ '!\\[' limit 8`)).rows;
console.log(s);
await c.end();
