import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { createClient } from "@supabase/supabase-js";
import { config as loadEnv } from "dotenv";
const here = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: join(here, "..", "..", ".env.local") });
const url = process.env.VITE_SUPABASE_URL!;
const ref = new URL(url).hostname.split(".")[0];
const password = process.env.SUPABASE_DB_PASSWORD!;
const c = new pg.Client({ connectionString: `postgresql://postgres.${ref}:${encodeURIComponent(password)}@aws-0-eu-west-1.pooler.supabase.com:5432/postgres`, ssl: { rejectUnauthorized: false } });
await c.connect();
console.log("=== RLS enabled on writing_activity? ===");
console.log((await c.query(`select relrowsecurity from pg_class where oid='public.writing_activity'::regclass`)).rows);
console.log("=== policies ===");
console.log((await c.query(`select policyname, cmd, roles from pg_policies where tablename='writing_activity'`)).rows);
await c.end();
const anon = createClient(url, process.env.VITE_SUPABASE_PUBLISHABLE_KEY!);
const { data, error } = await anon.from("writing_activity").select("day, words").eq("tenant","verbatim").order("day",{ascending:false}).limit(5);
console.log("=== anon SELECT writing_activity ===");
console.log("error:", error);
console.log("rows:", data);
