import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { config as loadEnv } from "dotenv";
const here = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: join(here, "..", "..", ".env.local") });
const url = process.env.VITE_SUPABASE_URL!;
const ref = new URL(url).hostname.split(".")[0];
const password = process.env.SUPABASE_DB_PASSWORD!;
const c = new pg.Client({ connectionString: `postgresql://postgres.${ref}:${encodeURIComponent(password)}@aws-0-eu-west-1.pooler.supabase.com:5432/postgres`, ssl: { rejectUnauthorized: false } });
await c.connect();
console.log("max id:", (await c.query(`select max(id) from public.posts`)).rows[0]);
console.log("\n=== 12 newest posts by created_at ===");
console.log((await c.query(`select id, title, status, type, slug, length(content_md) md, created_at, updated_at from public.posts order by created_at desc limit 12`)).rows);
console.log("\n=== 12 newest posts by id ===");
console.log((await c.query(`select id, title, status, type, length(content_md) md, created_at, updated_at from public.posts order by id desc limit 12`)).rows);
console.log("\n=== anything updated after 00:33 today ===");
console.log((await c.query(`select id, title, status, length(content_md) md, updated_at from public.posts where updated_at > '2026-07-10T00:33:10Z' order by updated_at desc limit 20`)).rows);
console.log("\n=== 'balcon' anywhere in content jsonb ===");
console.log((await c.query(`select id, title, status from public.posts where content::text ilike '%balcon%'`)).rows);
await c.end();
