import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { config as loadEnv } from "dotenv";
const here = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: join(here, "..", "..", ".env.local") });
const url = process.env.VITE_SUPABASE_URL!;
const ref = new URL(url).hostname.split(".")[0];
const password = process.env.SUPABASE_DB_PASSWORD!;
const c = new pg.Client({ connectionString: `postgresql://postgres.${ref}:${encodeURIComponent(password)}@aws-0-eu-west-1.pooler.supabase.com:5432/postgres`, ssl: { rejectUnauthorized: false } });
await c.connect();
console.log("=== writing_activity: count, range, tenants ===");
console.log((await c.query(`select tenant, count(*) n, min(day) mn, max(day) mx, sum(words) total from public.writing_activity group by tenant`)).rows);
console.log("\n=== writing_activity last 20 days ===");
console.log((await c.query(`select day, words, tenant from public.writing_activity order by day desc limit 20`)).rows);
console.log("\n=== increment_writing_activity RPC ===");
console.log((await c.query(`select proname, pg_get_function_identity_arguments(oid) args from pg_proc where proname='increment_writing_activity'`)).rows);
console.log("\n=== all public tables ===");
console.log((await c.query(`select table_name from information_schema.tables where table_schema='public' order by table_name`)).rows.map(r=>r.table_name).join(", "));
await c.end();
