// The six built-in themes (Theme API v1). Each is plain data that compileTheme()
// turns into CSS custom properties; `presets` are the theme's default page
// options, which a site's design overrides field by field (schema.ts).
// Audiences and the reasoning behind each: docs/proposals/blog-themes/README.md.

import type { ThemeSource } from "./compile";

export const THEMES: Record<string, ThemeSource> = {
  rubric: {
    api: 1, id: "rubric", name: "Rubric", version: "1.0.0",
    summary: "Book typography: one serif, red rubrication, dates in the margin.",
    audience: "Essayists, memoirists, critics and fiction writers: long, finished prose.",
    fonts: { display: "Crimson Pro", text: "Crimson Pro", ui: "Crimson Pro", mono: "system" },
    color: { paper: "#FCFBF8", ink: "#1D1814", accent: "#A8261B" },
    type: {
      text: { size: [18, 21], leading: 1.55, weight: 400, strong: 650 }, scale: [1.2, 1.25], figures: "oldstyle",
      display: { weight: 300, leading: 1.06, tracking: -0.012 }, title: { weight: 500, font: "display", tracking: -0.004 },
      dek: { font: "text", style: "italic" },
      brand: { font: "display", weight: 400, tracking: -0.015 },
      label: { font: "ui", case: "upper", tracking: 0.14, weight: 500, color: "accent", step: -1 },
      meta: { font: "ui", style: "italic", step: -1 },
      nav: { font: "ui", step: 0, weight: 400, tracking: 0.005 },
      roles: { brand: 4, manifesto: 4, postTitle: 5, collTitle: 5, cardTitle: 2, indexTitle: 1, leadTitle: 4, dek: 1, section: -1 },
    },
    space: { unit: 4, density: 1.1 },
    shape: { radius: 0, imageRadius: 0, avatar: "circle", rule: "solid", headerRule: "none", footerRule: "thin", leader: "none" },
    layout: { container: 1040, measure: 64, margin: 168, header: "stacked", headerAlign: "start", footer: "minimal", gridMin: 250, imageRatio: "3 / 2" },
    prose: { paragraph: "indent", ornament: "¶", quote: "accent", quoteItalic: true, link: "underline", caption: "center" },
    images: { filter: "soft" },
    format: { date: "long", readTime: "long", number: "No. {n}" },
    presets: {
      frame: { header: { tagline: true, sticky: false }, footer: { poweredBy: true } },
      home: { intro: { variant: "manifesto", stats: false }, feed: { mode: "latest", layout: "rows", card: "summary", lead: false, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      collection: { header: { variant: "banner", description: true, count: true, siblings: false }, posts: { layout: "rows", card: "summary", lead: false, group: "year", number: false, dek: true, readTime: false, collection: "auto", limit: "24" } },
      post: { header: { align: "center", dek: true, byline: true, readTime: true, number: true }, body: { dropCap: true, images: "column" }, after: { authorCard: true, details: false, nav: "inline", more: "none" } },
      author: { header: { variant: "center", avatar: true, links: true }, posts: { layout: "rows", card: "index", lead: false, group: "year", number: false, dek: false, readTime: false, collection: "show", limit: "24" } },
    },
  },
  edition: {
    api: 1, id: "edition", name: "Edition", version: "1.0.0",
    summary: "A modern magazine: big grotesque headlines, image-led grids, one ultramarine.",
    audience: "Small magazines, newsletters and multi-writer publications: many posts, images, sections.",
    fonts: { display: "Epilogue", text: "Epilogue", ui: "Epilogue", mono: "system" },
    color: { paper: "#FFFFFF", ink: "#0E0E13", accent: "#3525E6" },
    type: {
      text: { size: [16.5, 19], leading: 1.62, weight: 400, strong: 700 }, scale: [1.2, 1.333], figures: "lining",
      display: { weight: 800, leading: 0.98, tracking: -0.035 }, title: { weight: 700, font: "display", tracking: -0.018 },
      dek: { font: "text", style: "normal" },
      brand: { font: "display", weight: 800, tracking: -0.04 },
      label: { font: "ui", case: "smallcaps", tracking: 0.06, weight: 650, color: "accent", step: -1 },
      meta: { font: "ui", step: -1 },
      nav: { font: "ui", step: -1, weight: 600 },
      section: { font: "display" },
      roles: { brand: 3, manifesto: 5, postTitle: 5, collTitle: 5, cardTitle: 1, indexTitle: 1, leadTitle: 4, dek: 1, section: 2 },
    },
    space: { unit: 4, density: 1 },
    shape: { radius: 0, imageRadius: 0, avatar: "circle", rule: "solid", headerRule: "thick", footerRule: "thick", leader: "none", card: "plain" },
    layout: { container: 1240, measure: 66, margin: 0, wide: 150, header: "inline", footer: "columns", gridMin: 240, imageRatio: "4 / 3", leadRatio: "3 / 2" },
    prose: { paragraph: "space", ornament: "rule", quote: "strong", quoteItalic: false, link: "accent", caption: "start" },
    images: { filter: "none" },
    format: { date: "medium", readTime: "short", number: "#{n}" },
    presets: {
      frame: { header: { tagline: false, sticky: true }, footer: { poweredBy: true } },
      home: { intro: { variant: "compact", stats: false }, feed: { mode: "latest", layout: "grid", card: "card", columns: "3", lead: true, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      collection: { header: { variant: "plain", description: true, count: true, siblings: true }, posts: { layout: "grid", card: "card", columns: "3", lead: true, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      post: { header: { align: "start", width: "wide", dek: true, byline: true, readTime: true, number: false }, body: { dropCap: false, images: "wide" }, after: { authorCard: true, details: false, nav: "none", more: "3" } },
      author: { header: { variant: "split", avatar: true, links: true }, posts: { layout: "grid", card: "tile", columns: "3", lead: false, group: "none", number: false, dek: true, readTime: true, collection: "show", limit: "12" } },
    },
  },
  ledger: {
    api: 1, id: "ledger", name: "Ledger", version: "1.0.0",
    summary: "A notebook: numbered entries, ISO dates, a highlighter.",
    audience: "Working notes, reading logs and research journals: frequent short entries.",
    fonts: { display: "Public Sans", text: "Public Sans", ui: "JetBrains Mono", mono: "JetBrains Mono" },
    color: { paper: "#F4F4F0", ink: "#1C1D1F", accent: "#E9CF2B", highlight: "#F3E27A" },
    type: {
      text: { size: [16, 17], leading: 1.66, weight: 400, strong: 650 }, scale: [1.16, 1.2], figures: "lining",
      display: { weight: 650, leading: 1.14, tracking: -0.02 }, title: { weight: 600, font: "display", tracking: -0.008 },
      dek: { font: "text", style: "normal" },
      brand: { font: "ui", weight: 600, tracking: -0.01 },
      label: { font: "ui", case: "none", tracking: 0, weight: 400, color: "muted", step: -1 },
      meta: { font: "ui", step: -1 },
      nav: { font: "ui", step: -1, weight: 400 },
      roles: { brand: 0, manifesto: 2, postTitle: 4, collTitle: 3, cardTitle: 1, indexTitle: 0, leadTitle: 2, dek: 1, section: -1 },
    },
    space: { unit: 4, density: 0.9, row: 3 },
    shape: { radius: 2, imageRadius: 2, avatar: "square", rule: "solid", headerRule: "none", footerRule: "thin", leader: "dotted", card: "outline" },
    layout: { container: 1160, measure: 68, margin: 0, header: "rail", rail: 220, footer: "minimal", gridMin: 220, imageRatio: "4 / 3" },
    prose: { paragraph: "space", ornament: "§", quote: "strong", quoteItalic: false, link: "marker", caption: "start" },
    images: { filter: "mono" },
    format: { date: "iso", readTime: "min", number: "{n:03}" },
    presets: {
      frame: { header: { tagline: true, sticky: false }, footer: { poweredBy: true } },
      home: { intro: { variant: "none", stats: true }, feed: { mode: "latest", layout: "rows", card: "index", lead: false, group: "year", number: true, dek: false, readTime: false, collection: "auto", limit: "24" } },
      collection: { header: { variant: "plain", description: true, count: true, siblings: false }, posts: { layout: "rows", card: "index", lead: false, group: "year", number: true, dek: false, readTime: false, collection: "auto", limit: "24" } },
      post: { header: { align: "start", dek: true, byline: false, readTime: true, number: true }, body: { dropCap: false, images: "column" }, after: { authorCard: false, details: true, nav: "inline", more: "none" } },
      author: { header: { variant: "split", avatar: true, links: true }, posts: { layout: "rows", card: "index", lead: false, group: "year", number: true, dek: false, readTime: false, collection: "show", limit: "24" } },
    },
  },
  manual: {
    api: 1, id: "manual", name: "Manual", version: "1.0.0",
    summary: "Technical writing: code first, clear headings, a violet accent.",
    audience: "Engineers and technical writers: postmortems, deep dives, code-heavy posts, few images.",
    fonts: { display: "Red Hat Display", text: "Red Hat Display", ui: "Azeret Mono", mono: "Azeret Mono" },
    color: { paper: "#F7F8FA", ink: "#13161B", accent: "#6D28D9" },
    type: {
      text: { size: [16, 18], leading: 1.65, weight: 400, strong: 700 }, scale: [1.18, 1.25], figures: "lining",
      display: { weight: 750, leading: 1.1, tracking: -0.022 }, title: { weight: 700, font: "display", tracking: -0.012 },
      dek: { font: "text", style: "normal" },
      brand: { font: "display", weight: 800, tracking: -0.02 },
      label: { font: "ui", case: "none", tracking: 0, weight: 500, color: "accent", step: -1 },
      meta: { font: "ui", step: -1 },
      nav: { font: "display", step: -1, weight: 600 },
      roles: { brand: 1, manifesto: 3, postTitle: 5, collTitle: 4, cardTitle: 1, indexTitle: 0, leadTitle: 3, dek: 1, section: -1 },
    },
    space: { unit: 4, density: 1 },
    shape: { radius: 6, imageRadius: 6, avatar: "square", rule: "solid", headerRule: "thin", footerRule: "thin", leader: "none", card: "outline" },
    layout: { container: 1180, measure: 72, margin: 0, wide: 120, header: "inline", footer: "columns", gridMin: 260, imageRatio: "16 / 9" },
    prose: { paragraph: "space", ornament: "rule", quote: "accent", quoteItalic: false, link: "accent", caption: "start", code: "panel", codeSize: "text" },
    images: { filter: "none" },
    format: { date: "medium", readTime: "short", number: "#{n}" },
    presets: {
      frame: { header: { tagline: true, sticky: true }, footer: { poweredBy: true } },
      home: { intro: { variant: "compact", stats: false }, feed: { mode: "latest", layout: "rows", card: "summary", lead: false, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      collection: { header: { variant: "plain", description: true, count: true, siblings: true }, posts: { layout: "rows", card: "summary", lead: false, group: "year", number: false, dek: true, readTime: true, collection: "auto", limit: "24" } },
      post: { header: { align: "start", width: "content", dek: true, byline: true, readTime: true, number: false }, body: { dropCap: false, images: "wide" }, after: { authorCard: false, details: true, nav: "cards", more: "3" } },
      author: { header: { variant: "split", avatar: true, links: true }, posts: { layout: "rows", card: "index", lead: false, group: "year", number: false, dek: false, readTime: false, collection: "show", limit: "24" } },
    },
  },
  plate: {
    api: 1, id: "plate", name: "Plate", version: "1.0.0",
    summary: "A portfolio: big pictures, quiet type, captions that carry the detail.",
    audience: "Photographers, illustrators, architects and designers: the image is the post.",
    fonts: { display: "Sora", text: "Sora", ui: "Sora", mono: "system" },
    color: { paper: "#F8F8F6", ink: "#111111", accent: "#6B5C47" },
    type: {
      text: { size: [15, 17], leading: 1.65, weight: 400, strong: 600 }, scale: [1.2, 1.3], figures: "lining",
      display: { weight: 300, leading: 1.08, tracking: -0.02 }, title: { weight: 400, font: "display", tracking: -0.01 },
      dek: { font: "text", style: "normal" },
      brand: { font: "display", weight: 500, case: "upper", tracking: 0.2 },
      label: { font: "ui", case: "upper", tracking: 0.14, weight: 500, color: "muted", step: -1 },
      meta: { font: "ui", step: -1 },
      nav: { font: "ui", case: "upper", step: -1, weight: 500, tracking: 0.12 },
      roles: { brand: 0, manifesto: 3, postTitle: 5, collTitle: 4, cardTitle: 0, indexTitle: 0, leadTitle: 3, dek: 1, section: -1 },
    },
    space: { unit: 4, density: 1.15 },
    shape: { radius: 0, imageRadius: 0, avatar: "circle", rule: "solid", headerRule: "none", footerRule: "thin", leader: "none", card: "plain" },
    layout: { container: 1320, measure: 60, margin: 0, wide: 260, header: "stacked", headerAlign: "center", footer: "minimal", gridMin: 280, imageRatio: "4 / 5", coverRatio: "4 / 5", leadRatio: "3 / 2" },
    prose: { paragraph: "space", ornament: "· · ·", quote: "none", quoteItalic: false, link: "underline", caption: "center", code: "plain" },
    images: { filter: "none" },
    format: { date: "long", readTime: "short", number: "No. {n}" },
    presets: {
      frame: { header: { tagline: false, sticky: false }, footer: { poweredBy: true } },
      home: { intro: { variant: "none", stats: false }, feed: { mode: "latest", layout: "grid", card: "cover", columns: "3", lead: true, group: "none", number: false, dek: false, readTime: false, collection: "hide", limit: "12" } },
      collection: { header: { variant: "plain", description: true, count: false, siblings: true }, posts: { layout: "grid", card: "cover", columns: "3", lead: false, group: "none", number: false, dek: false, readTime: false, collection: "hide", limit: "24" } },
      post: { header: { align: "center", width: "content", dek: true, byline: false, readTime: false, number: true }, body: { dropCap: false, images: "wide" }, after: { authorCard: false, details: false, nav: "cards", more: "3" } },
      author: { header: { variant: "center", avatar: true, links: true }, posts: { layout: "grid", card: "cover", columns: "3", lead: false, group: "none", number: false, dek: false, readTime: false, collection: "hide", limit: "24" } },
    },
  },
  almanac: {
    api: 1, id: "almanac", name: "Almanac", version: "1.0.0",
    summary: "Practical and warm: rounded cards, a friendly serif, sections by season or subject.",
    audience: "Cooks, gardeners, makers and travel writers: how-tos with photos, recipes, lists.",
    fonts: { display: "Lora", text: "Plus Jakarta Sans", ui: "Plus Jakarta Sans", mono: "system" },
    color: { paper: "#F4F6EF", ink: "#1E2A22", accent: "#276B40" },
    type: {
      text: { size: [17, 18], leading: 1.7, weight: 400, strong: 700 }, scale: [1.2, 1.25], figures: "lining",
      display: { weight: 600, leading: 1.12, tracking: -0.01 }, title: { weight: 600, font: "display", tracking: -0.005 },
      dek: { font: "text", style: "normal" },
      brand: { font: "display", weight: 700, tracking: -0.01 },
      label: { font: "ui", case: "none", tracking: 0, weight: 650, color: "accent", step: -1 },
      meta: { font: "ui", step: -1 },
      nav: { font: "ui", step: -1, weight: 600 },
      section: { font: "display" },
      roles: { brand: 2, manifesto: 3, postTitle: 5, collTitle: 4, cardTitle: 1, indexTitle: 0, leadTitle: 3, dek: 1, section: 2 },
    },
    space: { unit: 4, density: 1 },
    shape: { radius: 14, imageRadius: 12, avatar: "circle", rule: "solid", headerRule: "none", footerRule: "thin", leader: "none", card: "surface" },
    layout: { container: 1200, measure: 64, margin: 0, wide: 140, header: "inline", footer: "columns", gridMin: 250, imageRatio: "4 / 3", leadRatio: "16 / 10" },
    prose: { paragraph: "space", ornament: "* * *", quote: "accent", quoteItalic: false, link: "accent", caption: "start", code: "panel" },
    images: { filter: "none" },
    format: { date: "medium", readTime: "short", number: "#{n}" },
    presets: {
      frame: { header: { tagline: false, sticky: false }, footer: { poweredBy: true } },
      home: { intro: { variant: "author", stats: false }, feed: { mode: "shelves", layout: "grid", card: "card", columns: "3", lead: false, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      collection: { header: { variant: "plain", description: true, count: true, siblings: true }, posts: { layout: "grid", card: "card", columns: "3", lead: true, group: "none", number: false, dek: true, readTime: true, collection: "auto", limit: "12" } },
      post: { header: { align: "start", width: "content", dek: true, byline: true, readTime: true, number: false }, body: { dropCap: false, images: "wide" }, after: { authorCard: true, details: false, nav: "cards", more: "3" } },
      author: { header: { variant: "split", avatar: true, links: true }, posts: { layout: "grid", card: "card", columns: "3", lead: false, group: "none", number: false, dek: true, readTime: true, collection: "show", limit: "12" } },
    },
  },
};

export const THEME_IDS = ["rubric", "edition", "ledger", "manual", "plate", "almanac"] as const;
export const DEFAULT_THEME = "rubric";
